POST https://potential-enigma-w9wxvxw77wvf5xp7-8788.app.github.dev/api/login HTTP/1.1

###

POST https://potential-enigma-w9wxvxw77wvf5xp7-8788.app.github.dev/api/login HTTP/1.1
content-type: application/json

{
    "email": "bob@example.com",
    "password": "12234"
}

###

POST https://potential-enigma-w9wxvxw77wvf5xp7-8788.app.github.dev/api/register HTTP/1.1
content-type: application/json

{
    "full_name": "bob marley",
    "email": "bob@example.com",
    "password": "12234"
}